// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using infrastructure.Database;

#nullable disable

namespace infrastructure.Database.Migrations
{
    [DbContext(typeof(XDbContext))]
    partial class XDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("infrastructure.Database.Models.ItemListDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("character varying(22)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ItemLists");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemListItemActionDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ListId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PricePerOne")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("ItemListItemAction");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemListSnapshotDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("BuffValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InvestedCapital")
                        .HasColumnType("numeric");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer");

                    b.Property<long>("ItemPriceRefreshId")
                        .HasColumnType("bigint");

                    b.Property<long>("ListId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SteamValue")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemPriceRefreshId");

                    b.HasIndex("ListId");

                    b.ToTable("ItemListValues");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemPriceDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Buff163PriceEur")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Buff163PriceUsd")
                        .HasColumnType("numeric");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemPriceRefreshId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SteamPriceEur")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SteamPriceUsd")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ItemPriceRefreshId");

                    b.ToTable("ItemPrices");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemPriceRefreshDbModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Buff163PricesLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SteamPricesLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ItemPriceRefresh");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemListItemActionDbModel", b =>
                {
                    b.HasOne("infrastructure.Database.Models.ItemListDbModel", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemListSnapshotDbModel", b =>
                {
                    b.HasOne("infrastructure.Database.Models.ItemPriceRefreshDbModel", "ItemPriceRefresh")
                        .WithMany()
                        .HasForeignKey("ItemPriceRefreshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("infrastructure.Database.Models.ItemListDbModel", "List")
                        .WithMany()
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPriceRefresh");

                    b.Navigation("List");
                });

            modelBuilder.Entity("infrastructure.Database.Models.ItemPriceDbModel", b =>
                {
                    b.HasOne("infrastructure.Database.Models.ItemPriceRefreshDbModel", "ItemPriceRefresh")
                        .WithMany()
                        .HasForeignKey("ItemPriceRefreshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemPriceRefresh");
                });
#pragma warning restore 612, 618
        }
    }
}
